import Darwin
import Foundation
@testable import FUMINIWAExperimental
import Testing

@Test("root-level self manifestだけを検査後にdigest対象から除外する")
func codexDeploymentManifestHasOneExactSelfExclusion() throws {
    let root = try makeManifestTemporaryRoot()
    defer { try? FileManager.default.removeItem(at: root) }
    try writeManifestFile(root: root, relativePath: "main.mjs", contents: "export {};\n")
    let baseline = try CodexDeploymentManifestVerifier.create(rootPath: root.path)

    try writeManifestFile(
        root: root,
        relativePath: CodexDeploymentManifestLimits.selfManifestPath,
        contents: "untrusted generated bytes"
    )
    let withSelf = try CodexDeploymentManifestVerifier.create(rootPath: root.path)
    #expect(withSelf.rootDigest == baseline.rootDigest)
    #expect(!withSelf.records.map(\.path).contains(CodexDeploymentManifestLimits.selfManifestPath))

    let nestedPath = "nested/\(CodexDeploymentManifestLimits.selfManifestPath)"
    try writeManifestFile(root: root, relativePath: nestedPath, contents: "covered")
    let withNestedName = try CodexDeploymentManifestVerifier.create(rootPath: root.path)
    #expect(withNestedName.rootDigest != baseline.rootDigest)
    #expect(withNestedName.records.map(\.path).contains(nestedPath))
}

@Test("symlink・hardlink・special fileをfail-closedで拒否する")
func codexDeploymentManifestRejectsUnsupportedFilesystemEntries() throws {
    let symlinkRoot = try makeManifestTemporaryRoot()
    defer { try? FileManager.default.removeItem(at: symlinkRoot) }
    try writeManifestFile(root: symlinkRoot, relativePath: "target", contents: "target")
    #expect(symlink("target", symlinkRoot.appending(path: "alias").path) == 0)
    #expect(manifestCreationError(symlinkRoot) == .symbolicLink)

    let hardlinkRoot = try makeManifestTemporaryRoot()
    let outsideHardlink = FileManager.default.temporaryDirectory
        .appending(path: "FUMINIWA-manifest-hardlink-\(UUID().uuidString)")
    defer {
        try? FileManager.default.removeItem(at: hardlinkRoot)
        try? FileManager.default.removeItem(at: outsideHardlink)
    }
    let original = try writeManifestFile(
        root: hardlinkRoot,
        relativePath: "original",
        contents: "same inode"
    )
    #expect(link(original.path, outsideHardlink.path) == 0)
    #expect(manifestCreationError(hardlinkRoot) == .hardLink)

    let specialRoot = try makeManifestTemporaryRoot()
    defer { try? FileManager.default.removeItem(at: specialRoot) }
    #expect(mkfifo(specialRoot.appending(path: "pipe").path, 0o600) == 0)
    #expect(manifestCreationError(specialRoot) == .unsupportedEntry)
}

@Test("危険modeとnoncanonical rootをspawn前identityとして拒否する")
func codexDeploymentManifestRejectsUnsafeModesAndRoots() throws {
    let root = try makeManifestTemporaryRoot()
    defer { try? FileManager.default.removeItem(at: root) }
    let file = try writeManifestFile(root: root, relativePath: "main.mjs", contents: "x")
    #expect(chmod(file.path, 0o666) == 0)
    #expect(manifestCreationError(root) == .invalidMode)

    #expect(
        capturedManifestError {
            _ = try CodexDeploymentManifestVerifier.create(rootPath: ".")
        } == .invalidRoot
    )

    let alias = root.deletingLastPathComponent().appending(path: "\(root.lastPathComponent)-alias")
    defer { try? FileManager.default.removeItem(at: alias) }
    #expect(symlink(root.path, alias.path) == 0)
    #expect(
        capturedManifestError {
            _ = try CodexDeploymentManifestVerifier.create(rootPath: alias.path)
        } == .invalidRoot
    )
}

@Test("relative pathはfatal UTF-8・component・path byte capを強制する")
func codexDeploymentManifestRejectsInvalidRelativePathBytes() throws {
    let invalidPaths = [
        Data(),
        Data([0x69, 0x6E, 0xFF]),
        Data("/a".utf8),
        Data("a/".utf8),
        Data("a//b".utf8),
        Data(".".utf8),
        Data("../a".utf8),
        Data(repeating: 0x61, count: 256)
    ]
    for bytes in invalidPaths {
        #expect(
            capturedManifestError {
                _ = try CodexDeploymentManifestVerifier.decodeCanonicalRelativePath(bytes)
            } == .invalidPath
        )
    }

    let oversizedPath = Data(
        String(repeating: "a/", count: 2048).appending("a").utf8
    )
    #expect(oversizedPath.count == 4097)
    #expect(
        capturedManifestError {
            _ = try CodexDeploymentManifestVerifier
                .decodeCanonicalRelativePath(oversizedPath)
        } == .resourceLimit
    )
    #expect(
        try CodexDeploymentManifestVerifier.decodeCanonicalRelativePath(
            Data("lib/日本語.mjs".utf8)
        ) == "lib/日本語.mjs"
    )
}

@Test("sparse fileとself fileのresource capをcontent read前に拒否する")
func codexDeploymentManifestRejectsSparseResourceOverages() throws {
    let fileRoot = try makeManifestTemporaryRoot()
    defer { try? FileManager.default.removeItem(at: fileRoot) }
    try makeSparseManifestFile(
        at: fileRoot.appending(path: "oversized.bin"),
        size: off_t(CodexDeploymentManifestLimits.maximumFileBytes + 1)
    )
    #expect(manifestCreationError(fileRoot) == .resourceLimit)

    let selfRoot = try makeManifestTemporaryRoot()
    defer { try? FileManager.default.removeItem(at: selfRoot) }
    try makeSparseManifestFile(
        at: selfRoot.appending(path: CodexDeploymentManifestLimits.selfManifestPath),
        size: off_t(CodexDeploymentManifestLimits.maximumCanonicalManifestBytes + 1)
    )
    #expect(manifestCreationError(selfRoot) == .resourceLimit)
}

@Test("directory列挙中にcovered entry capのexact境界と1件超過を判定する")
func codexDeploymentManifestBoundsDirectoryEnumerationBeforeCollection() throws {
    let exactRoot = try makeManifestTemporaryRoot()
    defer { try? FileManager.default.removeItem(at: exactRoot) }
    try writeManifestFile(root: exactRoot, relativePath: "only", contents: "x")
    let exactMetadata = try CodexDeploymentManifestFileIO.stableLstat(exactRoot.path)
    var exactCount = CodexDeploymentManifestLimits.maximumEntryCount - 1
    let exactComponents = try CodexDeploymentManifestDirectoryIO.components(
        at: exactRoot.path,
        initial: exactMetadata,
        parentRelativeBytes: Data(),
        coveredEntryCount: &exactCount
    )
    #expect(exactComponents == [Data("only".utf8)])
    #expect(exactCount == CodexDeploymentManifestLimits.maximumEntryCount)

    let overflowRoot = try makeManifestTemporaryRoot()
    defer { try? FileManager.default.removeItem(at: overflowRoot) }
    try writeManifestFile(root: overflowRoot, relativePath: "a", contents: "a")
    try writeManifestFile(root: overflowRoot, relativePath: "b", contents: "b")
    let overflowMetadata = try CodexDeploymentManifestFileIO.stableLstat(overflowRoot.path)
    var overflowCount = CodexDeploymentManifestLimits.maximumEntryCount - 1
    #expect(
        capturedManifestError {
            _ = try CodexDeploymentManifestDirectoryIO.components(
                at: overflowRoot.path,
                initial: overflowMetadata,
                parentRelativeBytes: Data(),
                coveredEntryCount: &overflowCount
            )
        } == .resourceLimit
    )
}

@Test("深いcanonical pathを再帰call stackに依存せず走査する")
func codexDeploymentManifestTraversesDeepPathIteratively() throws {
    let root = try makeManifestTemporaryRoot()
    defer { try? FileManager.default.removeItem(at: root) }

    let depth = 400
    var directory = root
    for _ in 0 ..< depth {
        directory.append(path: "a", directoryHint: .isDirectory)
        try FileManager.default.createDirectory(
            at: directory,
            withIntermediateDirectories: false
        )
        #expect(chmod(directory.path, 0o755) == 0)
    }

    let manifest = try CodexDeploymentManifestVerifier.create(rootPath: root.path)
    #expect(manifest.records.count == depth + 1)
    #expect(manifest.records.last?.path.utf8.count == depth * 2 - 1)
    #expect(manifest.records.allSatisfy { $0.kind == .directory })
}

private func manifestCreationError(_ root: URL) -> CodexDeploymentManifestError? {
    capturedManifestError {
        _ = try CodexDeploymentManifestVerifier.create(rootPath: root.path)
    }
}
